# Site settings
title: Chris Mitchelmore
email: chrismitchelmore@gmail.com
email-md5: a05a949a3cb8b7451ba048f5443b1481
url: https://chrismitchelmore.com
description: "Specialist iOS developer with full stack/startup experience and diverse skill set."
skills: "iOS Developer - User Experience Designer - Full Stack MVP"
meta_author: Chris Mitchelmore
company-details: "Company Number: 09106123 VAT #: 193 0288 02 <br>Registered Address:  Office 5 The Chantry, Hadham Road, Bishops Stortford, Hertfordshire, CM23 2QR"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Chris Mitchelmore
  location: Location
  social: Around the web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/crmitchelmore
  - title: stack-overflow
    url: http://stackoverflow.com/users/1453346/chris-mitchelmore
  - title: github
    url: https://github.com/crmitchelmore

# Postal address (add as many lines as necessary)
address:
  - line: Harrow
  - line: London
  - line: England

# Credits content
credits: 'Theme forked from <a href="https://github.com/jeromelachaud/freelancer-theme">jeromelachaud/freelancer-theme</a>.'

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
